# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBooking = channel.unary_unary(
                '/booking.BookingService/CreateBooking',
                request_serializer=booking__pb2.CreateBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.CreateBookingResponse.FromString,
                _registered_method=True)
        self.GetBooking = channel.unary_unary(
                '/booking.BookingService/GetBooking',
                request_serializer=booking__pb2.GetBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.GetBookingResponse.FromString,
                _registered_method=True)
        self.UpdateBooking = channel.unary_unary(
                '/booking.BookingService/UpdateBooking',
                request_serializer=booking__pb2.UpdateBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.UpdateBookingResponse.FromString,
                _registered_method=True)
        self.CancelBooking = channel.unary_unary(
                '/booking.BookingService/CancelBooking',
                request_serializer=booking__pb2.CancelBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.Empty.FromString,
                _registered_method=True)
        self.ListCustomerBookings = channel.unary_unary(
                '/booking.BookingService/ListCustomerBookings',
                request_serializer=booking__pb2.ListCustomerBookingsRequest.SerializeToString,
                response_deserializer=booking__pb2.ListCustomerBookingsResponse.FromString,
                _registered_method=True)
        self.CreateRooms = channel.unary_unary(
                '/booking.BookingService/CreateRooms',
                request_serializer=booking__pb2.CreateRoomsRequest.SerializeToString,
                response_deserializer=booking__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRooms = channel.unary_unary(
                '/booking.BookingService/GetRooms',
                request_serializer=booking__pb2.GetRoomsRequest.SerializeToString,
                response_deserializer=booking__pb2.GetRoomsResponse.FromString,
                _registered_method=True)
        self.CreateHotelEntry = channel.unary_unary(
                '/booking.BookingService/CreateHotelEntry',
                request_serializer=booking__pb2.CreateHotelEntryRequest.SerializeToString,
                response_deserializer=booking__pb2.CreateHotelEntryResponse.FromString,
                _registered_method=True)
        self.UpdateHotelEntry = channel.unary_unary(
                '/booking.BookingService/UpdateHotelEntry',
                request_serializer=booking__pb2.UpdateHotelEntryRequest.SerializeToString,
                response_deserializer=booking__pb2.UpdateHotelEntryResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBooking(self, request, context):
        """Create a new booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooking(self, request, context):
        """Get details of an existing booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBooking(self, request, context):
        """Update an existing booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBooking(self, request, context):
        """Cancel an existing booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomerBookings(self, request, context):
        """List all bookings for a given customer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRooms(self, request, context):
        """Get available room types and details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHotelEntry(self, request, context):
        """Create a new hotel entry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateHotelEntry(self, request, context):
        """Update an existing hotel entry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=booking__pb2.CreateBookingRequest.FromString,
                    response_serializer=booking__pb2.CreateBookingResponse.SerializeToString,
            ),
            'GetBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooking,
                    request_deserializer=booking__pb2.GetBookingRequest.FromString,
                    response_serializer=booking__pb2.GetBookingResponse.SerializeToString,
            ),
            'UpdateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBooking,
                    request_deserializer=booking__pb2.UpdateBookingRequest.FromString,
                    response_serializer=booking__pb2.UpdateBookingResponse.SerializeToString,
            ),
            'CancelBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBooking,
                    request_deserializer=booking__pb2.CancelBookingRequest.FromString,
                    response_serializer=booking__pb2.Empty.SerializeToString,
            ),
            'ListCustomerBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomerBookings,
                    request_deserializer=booking__pb2.ListCustomerBookingsRequest.FromString,
                    response_serializer=booking__pb2.ListCustomerBookingsResponse.SerializeToString,
            ),
            'CreateRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRooms,
                    request_deserializer=booking__pb2.CreateRoomsRequest.FromString,
                    response_serializer=booking__pb2.Empty.SerializeToString,
            ),
            'GetRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRooms,
                    request_deserializer=booking__pb2.GetRoomsRequest.FromString,
                    response_serializer=booking__pb2.GetRoomsResponse.SerializeToString,
            ),
            'CreateHotelEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHotelEntry,
                    request_deserializer=booking__pb2.CreateHotelEntryRequest.FromString,
                    response_serializer=booking__pb2.CreateHotelEntryResponse.SerializeToString,
            ),
            'UpdateHotelEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateHotelEntry,
                    request_deserializer=booking__pb2.UpdateHotelEntryRequest.FromString,
                    response_serializer=booking__pb2.UpdateHotelEntryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/CreateBooking',
            booking__pb2.CreateBookingRequest.SerializeToString,
            booking__pb2.CreateBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetBooking',
            booking__pb2.GetBookingRequest.SerializeToString,
            booking__pb2.GetBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/UpdateBooking',
            booking__pb2.UpdateBookingRequest.SerializeToString,
            booking__pb2.UpdateBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/CancelBooking',
            booking__pb2.CancelBookingRequest.SerializeToString,
            booking__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCustomerBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/ListCustomerBookings',
            booking__pb2.ListCustomerBookingsRequest.SerializeToString,
            booking__pb2.ListCustomerBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/CreateRooms',
            booking__pb2.CreateRoomsRequest.SerializeToString,
            booking__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetRooms',
            booking__pb2.GetRoomsRequest.SerializeToString,
            booking__pb2.GetRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateHotelEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/CreateHotelEntry',
            booking__pb2.CreateHotelEntryRequest.SerializeToString,
            booking__pb2.CreateHotelEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateHotelEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/UpdateHotelEntry',
            booking__pb2.UpdateHotelEntryRequest.SerializeToString,
            booking__pb2.UpdateHotelEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
